version: '3.4'

services:
  tfgsn-api:
    image: tfgsn-api
    build:
      context: ./ApiTFG
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
  tfgsn-app:
    image: tfgsn-app
    build:
      context: ./TfgSn.App
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://tfgsn-api:8080