name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/tfgsn-api:latest
          ${{ secrets.DOCKER_USERNAME }}/tfgsn-app:latest

    - name: SSH to Azure VM and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.AZURE_VM_HOST }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/tfgsn-api:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/tfgsn-app:latest
          docker-compose up -d